//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.13 at 02:38:07 PM EET 
//


package com.intellect25.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.intellect25.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 *
 * @author Riabchenko Aliona
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.intellect25.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Pavilion }
     *
     * @return Pavilion
     */
    public Pavilion createPavilion() {
        return new Pavilion();
    }

    /**
     * Create an instance of {@link Pavilion.Gem }
     *
     * @return Pavilion.Gem
     */
    public Pavilion.Gem createPavilionGem() {
        return new Pavilion.Gem();
    }

    /**
     * Create an instance of {@link Visual }
     *
     * @return Visual
     */
    public Visual createVisual() {
        return new Visual();
    }

    /**
     * Create an instance of {@link Stone }
     *
     * @return Stone
     */
    public Stone createStone() {
        return new Stone();
    }

}
