//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.13 at 02:38:07 PM EET 
//


package com.intellect25.entity;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 *
 * &lt;complexType
 *   &lt;complexContent
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"
 *       &lt;sequence
 *         &lt;element name="gem"
 *           &lt;complexType
 *             &lt;complexContent
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"
 *                 &lt;sequence
 *                   &lt;element name="stone" type="{http://www.example.com/mns}stone" maxOccurs="unbounded"
 *                 &lt;/sequence
 *               &lt;/restriction
 *             &lt;/complexContent
 *           &lt;/complexType
 *         &lt;/element
 *       &lt;/sequence
 *     &lt;/restriction
 *   &lt;/complexContent
 * &lt;/complexType
 * 
 * @author Riabchenko Aliona
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gem"
})
@XmlRootElement(name = "pavilion")
public class Pavilion {

    @XmlElement(required = true)
    protected Pavilion.Gem gem;

    /**
     * Gets the value of the gem property.
     * 
     * @return
     *     possible object is
     *     {@link Pavilion.Gem }
     *     
     */
    public Pavilion.Gem getGem() {
        return gem;
    }

    /**
     * Sets the value of the gem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pavilion.Gem }
     *     
     */
    public void setGem(Pavilion.Gem value) {
        this.gem = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     *
     * &lt;complexType
     *   &lt;complexContent
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"
     *       &lt;sequence
     *         &lt;element name="stone" type="{http://www.example.com/mns}stone" maxOccurs="unbounded"
     *       &lt;/sequence
     *     &lt;/restriction
     *   &lt;/complexContent
     * &lt;/complexType
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stone"
    })
    public static class Gem {

        @XmlElement(required = true)
        protected List<Stone> stone;

        /**
         * Gets the value of the stone property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stone property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         *
         *    getStone().add(newItem)
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Stone }
         * 
         * @return list of Stone
         */
        public List<Stone> getStone() {
            if (stone == null) {
                stone = new ArrayList<Stone>();
            }
            return this.stone;
        }

    }

}
