//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.13 at 02:38:07 PM EET 
//


package com.intellect25.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for visual complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * &lt;complexType name="visual"
 *   &lt;complexContent
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"
 *       &lt;sequence
 *         &lt;element name="color" type="{http://www.example.com/mns}color"
 *         &lt;element name="transparency" type="{http://www.example.com/mns}transparency"
 *         &lt;element name="cutting" type="{http://www.example.com/mns}cutting"
 *       &lt;/sequence
 *     &lt;/restriction
 *   &lt;/complexContent
 * &lt;/complexType
 * 
 * @author Riabchenko Aliona
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "visual", propOrder = {
    "color",
    "transparency",
    "cutting"
})
public class Visual {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Color color;
    protected int transparency;
    @XmlSchemaType(name = "integer")
    protected int cutting;

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link Color }
     *     
     */
    public Color getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link Color }
     *     
     */
    public void setColor(Color value) {
        this.color = value;
    }

    /**
     * Gets the value of the transparency property.
     *
     * @return transparency
     */
    public int getTransparency() {
        return transparency;
    }

    /**
     * Sets the value of the transparency property.
     * 
     */
    public void setTransparency(int value) {
        this.transparency = value;
    }

    /**
     * Gets the value of the cutting property.
     *
     * @return cutting
     */
    public int getCutting() {
        return cutting;
    }

    /**
     * Sets the value of the cutting property.
     * 
     */
    public void setCutting(int value) {
        this.cutting = value;
    }

}
